services:
  - type: web
    name: store-api
    runtime: java
    plan: free
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/store-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_VERSION
        value: "17"
      - key: STAGING_DB_PASSWORD
        sync: false
